# Generated by Django 5.2.1 on 2026-09-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensekey',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='licensekey',
            name='uses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_access',
        ),
        migrations.AddField(
            model_name='licensekey',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='use_server_key',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jarvis_license', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='uses_main_data',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HermesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('status', models.CharField(choices=[('running', 'läuft'), ('done', 'fertig'), ('failed', 'fehlgeschlagen')], default='running', max_length=10)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hermes_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
